name: easyhub_admin_app 
description: A Flutter app for EasyHub Admin functionalities.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0  
